# Generated by Django 3.0.3 on 2020-04-09 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(null=True)),
                ('property_name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskrunner.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(null=True)),
                ('asin', models.CharField(max_length=20, null=True, unique=True)),
                ('model_number', models.CharField(max_length=50, null=True, unique=True)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('product_title', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('bsr', models.FloatField(null=True)),
                ('customer_rating', models.IntegerField(null=True)),
                ('rating_amount', models.IntegerField(null=True)),
                ('published', models.DateTimeField(null=True)),
                ('dim_x', models.FloatField(null=True)),
                ('dim_y', models.FloatField(null=True)),
                ('dim_z', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('shipping_weight', models.FloatField(null=True)),
                ('product_brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskrunner.ProductBrand')),
            ],
        ),
    ]
