# Generated by Django 3.0.5 on 2020-04-21 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_parser', '0002_auto_20200417_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(null=True)),
                ('page_html', models.TextField()),
            ],
        ),
    ]
